### PR TITLE
change package name to "tetra"

### LINKED ISSUE #37: Move package name from "tetraframework" to "tetra"
Hi @samwillis, as you may have noticed, I had asked TheCulliganMan to hand the `tetra` PyPi package into your hands, so you can use it for Tetra - because e.g. PyCharm has some problems when tetra is not installed: e.g. with `import tetra`  it tries to help you and ask to install the "tetra" package. which is not your Tetra framework, but a package by TheCulliganMan, https://pypi.org/project/tetra/. He doesn't need this package any more, so he would be willing to pass you the handle for that package on PyPi.

I hope I am not too eager, but I think this would be a great booster for Tetra to be found and used.
Please get in contact with him if that is ok for you, and deal the details.

If I'm too enthusiastic, please tell me. ;-)

### LINKED ISSUE #54: Missing example for Alpine.js
As [discussed](https://github.com/tetra-framework/tetra/discussions/30), the backend usage is well documented, but the Alpine part ant the combination of the two lacks an example.

### PR DESCRIPTION
**Pull request by nerdoc**
* substantial documentation update
* MkDocs as base
* readthedocs config

fixes #54
fixes #37

### CODE REVIEW

**Comment by nerdoc** [comment]
For merging the following conditions must be met:
* [ ] tetra pypi package must transferred by @TheCulliganMan to @nerdoc 
* [ ] tetra readthedocs package [tetra](https://readthedocs.org/projects/tetra/) must be also transferred to nerdoc
* [ ] @samwillis must add a readthedocs webhook to tetra settings or grant permissions to @nerdoc

**Comment by TheCulliganMan** [comment]
Hey @nerdoc, thank you for the reminder.  I added you as maintainer on both of these. You should have emails sent over.  If this gives you permission to remove me, go for it, once you accept, i'll gladly remove myself as well.

**Comment by nerdoc** [comment]
Thank you very much, really appreciate your friendliness and openness. That can't be taken for granted. Hope sometimes you get something back for that from somewhere. If you need anything I can do for you, anytime.
So I will remove you from the two projects, and will advance with the "tetraframework" & rename it to "tetra" then. 
Thanks again.

**Comment by TheCulliganMan** [comment]
Thank you!  It was nice meeting you and glad I could help!

**Pull request merged**
